config/routes.rb
WikiApp::Application.routes.draw do

  resources :wikis do
    resources :comments
  end 
      
  root :to => 'pages#home'
  
  match '/about',        :to => 'pages#about'
  match '/findwiki',     :to => 'wikis#new'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :wiki_id
  
  belongs_to :wiki
  
  validates :content, :presence => true, :length => { :maximum => 200 }
  validates :wiki_id, :presence => true
  
  default_scope :order => 'comments.created_at DESC'
end

app/models/wiki.rb
require 'nokogiri'
require 'open-uri'

class Wiki < ActiveRecord::Base
  attr_accessible :name, :content
  
  has_many :comments
  
  name_regexp = /\A[a-zA-Z1-9\s\:\(\)]+\z/i
  
  validates :name, :presence => true,
                   :length     => { :maximum => 50 },
                   :format     => { :with => name_regexp },
		           :uniqueness => { :case_sensitive => false }
		   
  #validates_with ContentValidator
  
  default_scope :order => 'wikis.name ASC'

  before_save :get_content
  
end

def get_content
  wiki_url = "http://en.wikipedia.org/wiki/#{name.gsub(' ','_')}"
  page = Nokogiri::HTML(open(wiki_url))
  self.content = "#{page.css('p')[0].text} \n\n #{page.css('p')[1].text} \n\n #{page.css('p')[2].text}"
end

def get_info
  return "Wiki name: #{:name}\n Created at: #{:created_at}"
end
#class ContentValidator < ActiveModel::Validator
#  def validate(record)
#    if error(record.name)
#      record.errors[:base] = "No such Wikipedia entry"
#    end
#  end
#  
#  private
#
#	def error(name)
#	  begin
#	    wiki_url = "http://en.wikipedia.org/wiki/#{name.gsub(' ','_')}"
#	    page = Nokogiri::HTML(open(wiki_url))
#        return false
#	  rescue Exception => e
#	    return true
#	  end
#	end
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  	@wiki = Wiki.find(params[:wiki_id])
    @comments = @wiki.comments.paginate(:page => params[:page])
    @title = "All comments"
  end

  def create
  	@wiki = Wiki.find(params[:wiki_id])
    @comment = @wiki.comments.build(params[:comment])
    if @comment.save
      redirect_to @wiki, :flash => { :success => "Comment posted!" }
    else
      redirect to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  def index
    @wikis = Wiki.paginate(:page => params[:page])
    @title = "All articles"
  end
  
  def show
    @wiki = Wiki.find(params[:id])
    @comment = Comment.new
    @comment.wiki_id = @wiki.id
    @comments = @wiki.comments.paginate(:page => params[:page])
    @title = @wiki.name
  end
  
  def new
    @wiki = Wiki.new
    @title = "Find a Wiki"
  end
  
  def create
    @wiki = Wiki.new(params[:wiki])
    if @wiki.save
      redirect_to @wiki
    else 
      @title = "Find a Wiki"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis
  def title
    base_title = "WikiWars"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo 
    image_tag("wikiwars.png", :alt => "WikiWars", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wikis_helper.rb
module WikisHelper

end

app/views/comments/_comment.html.erb
<tr>
  <td class="comment">
    <span class="content"><%= comment.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(comment.created_at) %> ago.
    </span>
  </td>
</tr>

app/views/comments/index.html.erb
<h3 class="commindex">All comments for</h3>
<h1><%= @wiki.name %></h1>
<% if @wiki.comments.any? %>
  <table class="comments" summary="Wiki comments">
    <%= render @comments %>
  </table>
  <%= will_paginate @comments %>
<% else %>
  <p class="nothing">There is nothing here! Be the first to comment!</p> 
  <p class="postconds">(In keeping with the spirit of the site, preferably something inflammatory)</p> 
<% end %>



app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "All Articles", wikis_path %></li>
      <li><%= link_to "Find a Wiki", findwiki_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<%= link_to logo, root_path %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
      	<% flash.each do |key, value| %>
      	  <div class="flash <%= key %>"><%= value %></div>
      	<% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="up">About</h1>

<p class="about">This is an app that lets you fetch an article from Wikipedia and comment on it right here on WikiWars!</p>

app/views/pages/home.html.erb
<h1 class="up">Welcome to WikiWars!</h1>
<p>Share your thoughts about a topic of your choosing. Pick a topic and go to WikiWar!</p><br />
<%= link_to "Find a Wiki", findwiki_path, :class => "wiki_button round" %>

app/views/shared/_comment_form.html.erb
<%= form_for([@wiki, @comment]) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post!" %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <br /><br /><br />
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
    </h2>
    <ul>
    <%= object.errors.full_messages.each do |message| %>
      <li><%= "#{message}" %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/wikis/_wiki.html.erb
<li>
  <%= link_to wiki.name, wiki %> - <%= wiki.comments.count %>
</li>

app/views/wikis/index.html.erb
<h1>All articles</h1>

<%= will_paginate %>
<br />
<ul class="wikis">
  <%= render @wikis %>
</ul>
<%= will_paginate %>


app/views/wikis/new.html.erb
<h1 class="up">Find a Wiki!</h1>
<p>Use the field below to search Wikipedia for a topic of your choice.</p>

<%= form_for(@wiki) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name, "Topic" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Get it!" %>
  </div>
  
<% end %>

app/views/wikis/show.html.erb
<h1 class="wiki"><%= @wiki.name %></h1>
<strong>Comments</strong> <%= link_to @wiki.comments.count, "#{wiki_path}/comments" %> <br />
<strong>Wikipedia</strong> <%= link_to "URL", "http://en.wikipedia.org/wiki/ #{@wiki.name.gsub(' ','_')}", :target => '_blank' %><br />
<strong>WikiWar started</strong> <%= time_ago_in_words(@wiki.created_at) %> ago.<br />
<br />
<p><%= @wiki.content %></p>
<br />
<span class="comheader">Leave a comment and let the WikiWar begin!</span><p class="comconds">(max 200 characters)</p>
<%= render 'shared/comment_form' %>
<% if @wiki.comments.any? %>
  <table class="comments" summary="Wiki comments">
    <%= render @comments %>
  </table>
  <%= will_paginate @comments %>
<% end %>
